export const userData = [
  {
    name: "Jan",
    ActiveUser: 4000,
  },
  {
    name: "Feb",
    ActiveUser: 3000,
  },
  {
    name: "Mar",
    ActiveUser: 2000,
  },
  {
    name: "Apr",
    ActiveUser: 2780,
  },
  {
    name: "May",
    ActiveUser: 1890,
  },
  {
    name: "Jun",
    ActiveUser: 2390,
  },
  {
    name: "Jul",
    ActiveUser: 2190,
  },
  {
    name: "Aug",
    ActiveUser: 5290,
  },
  {
    name: "Sep",
    ActiveUser: 4190,
  },
  {
    name: "Oct",
    ActiveUser: 3190,
  },
  {
    name: "Nov",
    ActiveUser: 4390,
  },
  {
    name: "Dec",
    ActiveUser: 5490,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 6000,
  },
];
export const userRows = [
  {
    id: 1,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 2,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 3,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 4,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 5,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 6,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 7,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 8,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 9,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 10,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
  {
    id: 11,
    username: "John Snow",
    avatar: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    email: "hone1@gmail.com",
    status: "active",
    transaction: "$540.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 2,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 3,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 4,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 5,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 6,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 7,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 8,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 9,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 10,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
  {
    id: 11,
    name: "Earrings ",
    img: "https://drive.google.com/uc?export=view&id=1ICKdBOEee6rwQXzlaprqWciN-IcxI-JD",
    stock: 123,
    status: "active",
    price: "$200.00",
  },
];
